// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX7lvIrNZx-1h6Gbg2TOtL6OAf_h6tlwM',
    appId: '1:869458511378:web:cfc520da1cce35f73dbacb',
    messagingSenderId: '869458511378',
    projectId: 'market1-86af5',
    authDomain: 'market1-86af5.firebaseapp.com',
    storageBucket: 'market1-86af5.firebasestorage.app',
    measurementId: 'G-2P845D2CC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuu2YO7QEjWsdKfWGrrsWeD5nxXB-V2xI',
    appId: '1:869458511378:android:897e5d9408fe29fd3dbacb',
    messagingSenderId: '869458511378',
    projectId: 'market1-86af5',
    storageBucket: 'market1-86af5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO11-sAs9pqPQUHO__3P5nJcNgDdWeinU',
    appId: '1:869458511378:ios:47c356827b62242e3dbacb',
    messagingSenderId: '869458511378',
    projectId: 'market1-86af5',
    storageBucket: 'market1-86af5.firebasestorage.app',
    iosClientId: '869458511378-7lh0mrivpsp7ds44g3bdvr3d1l4b6ndi.apps.googleusercontent.com',
    iosBundleId: 'com.example.market1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO11-sAs9pqPQUHO__3P5nJcNgDdWeinU',
    appId: '1:869458511378:ios:47c356827b62242e3dbacb',
    messagingSenderId: '869458511378',
    projectId: 'market1-86af5',
    storageBucket: 'market1-86af5.firebasestorage.app',
    iosClientId: '869458511378-7lh0mrivpsp7ds44g3bdvr3d1l4b6ndi.apps.googleusercontent.com',
    iosBundleId: 'com.example.market1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX7lvIrNZx-1h6Gbg2TOtL6OAf_h6tlwM',
    appId: '1:869458511378:web:010f43856b154e3a3dbacb',
    messagingSenderId: '869458511378',
    projectId: 'market1-86af5',
    authDomain: 'market1-86af5.firebaseapp.com',
    storageBucket: 'market1-86af5.firebasestorage.app',
    measurementId: 'G-DZC827KVFW',
  );

}